name: Deploy Draft

# Given a pull request:
# 1. On open or reopen check if there is a duplicate draft (and do not allow)
# 2. On update deploy the draft to the site
# Removed files are not removed until merge
on:
  pull_request:
    paths:
      - proposals/*.md

jobs:
  deploy-draft:
    runs-on: ubuntu-latest
    if: (github.ref != 'refs/heads/gh-pages')
    steps:
      - name: Checkout
        if: (github.ref != 'refs/heads/gh-pages')
        uses: actions/checkout@v2

      - name: Save Event Name
        env:
           event_name: ${{ github.event.action }}
        run:
           printf "${event_name}\n"
           check_duplicates=false
           if [[ "${event_name}" == "reopened" ]] || [[ "${event_name}" == "opened" ]]; then
               check_duplicates=true
           fi
           printf "Checking duplicates? ${check_duplicates}\n"
           echo "check_duplicates=${check_duplicates}" >> $GITHUB_ENV

      - name: Find changed files to add
        id: changed_files
        env:
          changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
        run: python .github/scripts/deploy.py draft ${changed_files}

      - name: Clone Pages        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: /bin/bash .github/scripts/clone.sh

      - name: Check for Duplicates
        if: ${{ env.check_duplicates == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: /bin/bash .github/scripts/check_duplicates.sh

      - name: Update Drafts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          proposals: ${{ steps.changed_files.outputs.proposals }}
        run: /bin/bash .github/scripts/deploy_drafts.sh
