
# Given a pull request, deploy the draft to the site
# Removed files are not removed until merge
on:
  pull_request: []

jobs:
  deploy-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Find Changed Proposals
        id: changed-files
        uses: tj-actions/changed-files@32d6fb28f082f273420574e9de0a30be993bba58
        with:
          separator: " "

      - name: Find changed files to add
        id: changed_files
        env:
          changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
        run: /bin/bash .github/scripts/deploy.py draft ${changed_files}

      - name: Checkout New Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_FROM: ${{ github.event.inputs.branch }}
          proposals: ${{ steps.changed_files.outputs.proposals }}
        run: /bin/bash .github/scripts/deploy_drafts.sh
