
# Given a pull request:
# 1. On open or reopen check if there is a duplicate draft (and do not allow)
# 2. On update deploy the draft to the site
# Removed files are not removed until merge
on:
  pull_request:
    paths:
      - proposals/

jobs:
  deploy-draft:
    runs-on: ubuntu-latest
    if: (github.ref != 'refs/heads/gh-pages')
    steps:
      - name: Checkout
        if: (github.ref != 'refs/heads/gh-pages')
        uses: actions/checkout@v2

      - name: Find Changed Proposals
        id: changed-files
        uses: tj-actions/changed-files@32d6fb28f082f273420574e9de0a30be993bba58
        with:
          separator: " "

      - name: Find changed files to add
        id: changed_files
        env:
          changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
        run: python .github/scripts/deploy.py draft ${changed_files}

      - name: Clone Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: /bin/bash .github/scripts/clone.sh

      - name: Check for Duplicates
        if: (github.event.pull_request.opened == true || github.event.pull_request.reopened == true)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          proposals: ${{ steps.changed_files.outputs.proposals }}
        run: /bin/bash .github/scripts/check_duplicates.sh

      - name: Update Drafts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          proposals: ${{ steps.changed_files.outputs.proposals }}
        run: /bin/bash .github/scripts/deploy_drafts.sh
